---
#
# MDEX
#

- set_fact:
    install_archive: "V46002-01.zip"
    install_executable: "OCmdex6.5.1-Linux64_829811.sh"

- name: temporary directory for install
  register: mktemp
  command: mktemp -d

- name: download installation archive
  get_url:
  args:
    url: "{{ install_archive_url }}"
    dest: "{{ playbook_dir }}/{{ install_archive }}"
  when: install_archive_url is defined

- name: expand MDEX archive
  unarchive: 
    src="{{ install_archive }}"
    dest="{{ mktemp.stdout }}"
    creates="{{ mktemp.stdout }}/{{ install_executable }}"

- name: install mdex
  command: "{{ mktemp.stdout }}/{{ install_executable }} --silent --target {{ install_root }}" 
  args:
    creates: "{{ install_root }}/endeca/MDEX"

#- name: source mdex environment vars
#  lineinfile: 
#    dest=/home/{{ endeca_user }}/.bashrc 
#    line="source {{ install_root }}/endeca/MDEX/6.5.1/mdex_setup_sh.ini"

- name: clean up temporary directory
  file: 
    state=absent 
    path="{{ mktemp.stdout }}"
